# render.yaml
services:
  - type: web
    name: assistive-living-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    # This command MUST match your folder structure.
    startCommand: gunicorn Assistive_living.app:app
    # The following two sections must be indented like this.
    buildpacks:
      - url: https://github.com/heroku/heroku-buildpack-apt
    aptPackages:
      - ffmpeg