# render.yaml
services:
  - type: web
    name: sound-classifier
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    buildpacks: # Correctly indented
      - url: https://github.com/heroku/heroku-buildpack-apt
    aptPackages: # Correctly indented
      - ffmpeg